(cl:defpackage world_percept_assig-srv
  (:use )
  (:export
   "SETINITTIAGOPOSE"
   "<SETINITTIAGOPOSE-REQUEST>"
   "SETINITTIAGOPOSE-REQUEST"
   "<SETINITTIAGOPOSE-RESPONSE>"
   "SETINITTIAGOPOSE-RESPONSE"
   "UPDATEOBJECTLIST"
   "<UPDATEOBJECTLIST-REQUEST>"
   "UPDATEOBJECTLIST-REQUEST"
   "<UPDATEOBJECTLIST-RESPONSE>"
   "UPDATEOBJECTLIST-RESPONSE"
  ))

